#!/bin/bash -e
tmp=$(mktemp)
dir=$(dirname $tmp)
pushd $dir
cat > $tmp << EOT
\documentclass{article}
\usepackage[active,tightpage]{preview}
\begin{document}
\begin{preview}
$@
\end{preview}
\end{document}
EOT

pdflatex -halt-on-error $tmp > /dev/null
popd
pdfless $dir/tmp.pdf
